### ISSUE TITLE
how run?

### ISSUE THREAD

**Issue by johnfelipe** [Mourula/XmlTranslate#1]
```
root@ubuntu20:~/XmlTranslate# python3 main.py
Using Colombia server backend.
ERROR: Give XML file as an argument.

```

**Comment by Mourula** [comment]
Hi. Thank you for your question.
As stated in the README and also in the error message, you need to give the filename of (and possibly the path to) the XML file as a command line argument.

For example:
`$ python3 main.py sample.xml`

Notice, that the code and repository are made for a particular XML structure (see the sample file) and would probably need modifications to serve your purpose.
